#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
#exec git diff-index --check --cached $against --

# linter java : checkstyle
# this is the magic: 
# retrieve all files in staging area that are added, modified or renamed
# but no deletions etc
FILES=$(git diff-index --name-only --cached --diff-filter=ACMR $against -- | grep .java)
#todo android_checks
CHECK_CONF_FILE="$(git rev-parse --show-toplevel)/checkstyle/android_checks.xml"
if [ "$FILES" = "" ]; then
	exit 0
fi
FILES_TO_CHECK=""
for FILE in $FILES
do
    FILES_TO_CHECK="$FILES_TO_CHECK $FILE"
done
if [ "$FILES_TO_CHECK" = "" ]; then
    exit 0
fi

CHECK_RESULT=$(checkstyle -c $CHECK_CONF_FILE $FILES_TO_CHECK)
r=$?
if [ $r -ne 0 ]; then
	echo "$CHECK_RESULT"
	echo '------------------------------------------------'
	echo '------------------git commit失败----------------'
	echo '------------------------------------------------'
	echo '代码不规范。请遵守Java官方规范和Android官方补充规范：'
        echo 'Java官方规范：'
        echo '英文：http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html'
        echo '汉字翻译：http://www.huihoo.org/code/java_code_conventions.html'
        echo 'Android官方补充规范：'
        echo '英文：https://source.android.com/source/code-style.html'
        echo '汉字翻译：http://blog.sina.com.cn/s/blog_48d491300100zwzg.html'
	echo '修改后，请重新git add'
fi

exit $r
